// frontend-react/src/pages/EventsPage/EventsPage.jsx
import { useEffect, useState } from 'react'
import { EventCard } from '@/components/EventCard/EventCard.jsx'
import { EmptyState } from '@/components/shared/EmptyState.jsx'
import { ErrorState } from '@/components/shared/ErrorState.jsx'
import { LoadingSpinner } from '@/components/shared/LoadingSpinner.jsx'
import { PageHeader } from '@/components/shared/PageHeader.jsx'
import './EventsPage.css'

const API_URL = import.meta.env.VITE_API_URL
const API_KEY = import.meta.env.VITE_API_KEY

export function EventsPage() {
  const [events, setEvents] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  async function fetchEvents() {
    setLoading(true)
    setError(null)
    try {
      const response = await fetch(`${API_URL}/api/events`, {
        headers: {
          'x-api-key': API_KEY,
        },
      })

      if (!response.ok) throw new Error('Failed to fetch events')
      const data = await response.json()
      setEvents(Array.isArray(data) ? data : [])
    } catch (err) {
      setError(err?.message || String(err))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchEvents()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <div className="page">
      <PageHeader title="Come see us play live! - React" />

      {loading ? <LoadingSpinner message="Loading events..." /> : null}

      {!loading && error ? <ErrorState message={error} onRetry={fetchEvents} /> : null}

      {!loading && !error && events.length === 0 ? (
        <EmptyState icon="🎤" title="No events yet" message="Time to book some gigs!" />
      ) : null}

      {!loading && !error && events.length > 0 ? (
        <div className="events-grid">
          {events.map((event, index) => (
            <EventCard
              key={event.id}
              event={event}
              animationDelay={index * 0.1}
              commentCount={0}
              onOpenComments={() => {
                // Comment modal port will come next
              }}
            />
          ))}
        </div>
      ) : null}
    </div>
  )
}

// frontend/src/views/EventsPage.vue
<template>
  <div class="page">
    <PageHeader
      title="Upcoming Events"
      subtitle="Your gigs and setlists, all in one place"
    />

    <LoadingSpinner v-if="loading" message="Loading events..." />

    <ErrorState
      v-else-if="error"
      :message="error"
      @retry="fetchEvents"
    />

    <EmptyState
      v-else-if="events.length === 0"
      icon="🎤"
      title="No events yet"
      message="Time to book some gigs!"
    />

    <div v-else class="events-grid">
      <EventCard
        v-for="(event, index) in events"
        :key="event.id"
        :event="event"
        :animation-delay="index * 0.1"
      />
    </div>
  </div>
</template>

<script>
import EventCard from '@/components/EventCard.vue'
import PageHeader from '@/components/PageHeader.vue'
import LoadingSpinner from '@/components/LoadingSpinner.vue'
import EmptyState from '@/components/EmptyState.vue'
import ErrorState from '@/components/ErrorState.vue'

export default {
  name: 'EventsPage',
  components: {
    EventCard,
    PageHeader,
    LoadingSpinner,
    EmptyState,
    ErrorState
  },
  data() {
    return {
      events: [],
      loading: false,
      error: null
    }
  },
  async mounted() {
    await this.fetchEvents()
  },
  methods: {
    async fetchEvents() {
      this.loading = false
      this.error = null
      try {
        // Run API call and minimum delay in parallel
        const [response] = await Promise.all([
          fetch(`${import.meta.env.VITE_API_URL}/api/events`, {
            headers: {
              'x-api-key': import.meta.env.VITE_API_KEY
            }
          }),
        //   new Promise(resolve => setTimeout(resolve, 2000))
        ])
        if (!response.ok) throw new Error('Failed to fetch events')
        this.events = await response.json()
      } catch (err) {
        this.error = err.message
      } finally {
        this.loading = false
      }
    }
  }
}
</script>

<style scoped>
.events-grid {
  display: grid;
  gap: 1rem;
}
</style>
